// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM9j00v_p-hfc-CC6ROzaUyFWDRFR-1uE',
    appId: '1:437912112652:web:93090b4d026499f8342829',
    messagingSenderId: '437912112652',
    projectId: 'wisata-2efaf',
    authDomain: 'wisata-2efaf.firebaseapp.com',
    storageBucket: 'wisata-2efaf.appspot.com',
    measurementId: 'G-ZHCW4HZRP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQYrmakpiXApPca9cuhI8V0oAFQczi3w',
    appId: '1:437912112652:android:cf1f83b0e9ab7bdf342829',
    messagingSenderId: '437912112652',
    projectId: 'wisata-2efaf',
    storageBucket: 'wisata-2efaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6f_mjsL2Yue0gBzbITKRM3vW64oMPCI4',
    appId: '1:437912112652:ios:af8f73cd1236746a342829',
    messagingSenderId: '437912112652',
    projectId: 'wisata-2efaf',
    storageBucket: 'wisata-2efaf.appspot.com',
    iosBundleId: 'com.example.wisataTour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6f_mjsL2Yue0gBzbITKRM3vW64oMPCI4',
    appId: '1:437912112652:ios:af8f73cd1236746a342829',
    messagingSenderId: '437912112652',
    projectId: 'wisata-2efaf',
    storageBucket: 'wisata-2efaf.appspot.com',
    iosBundleId: 'com.example.wisataTour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM9j00v_p-hfc-CC6ROzaUyFWDRFR-1uE',
    appId: '1:437912112652:web:d11662e44f9b01cf342829',
    messagingSenderId: '437912112652',
    projectId: 'wisata-2efaf',
    authDomain: 'wisata-2efaf.firebaseapp.com',
    storageBucket: 'wisata-2efaf.appspot.com',
    measurementId: 'G-MV6VRLH4CS',
  );
}
